ALTER TABLE members ADD COLUMN IF NOT EXISTS total_pv INTEGER DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS pv INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_pv INTEGER DEFAULT 0;
